#!/bin/bash
# Copyright 2016 Jan Verbeek
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and this
# notice are preserved. This file is offered as-is, without any warranty.

if [ $# = 0 ]; then
    echo "Usage: $0 command [argument ...]" >&2
    exit
fi

# recursion is used to keep process substitutes alive
main () {
    for arg in "${@:i+1}"; do
        if [[ "$arg" =~ ^[[:alpha:]][[:alnum:]+.-]*:// ]]; then
            main "${@:1:i}" <(curl -LSs "$arg") "${@:i+2}"
        fi
        let i++
    done
    exec -- "$@"
}

i=0
main "$@"
